version: 2.1

jobs:
  checkstyle:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
      - run:
          name: Checkstyle
          command: mvn -q checkstyle:check
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

  build:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: mvn -q clean compile
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

  test:
    docker:
      - image: cimg/openjdk:21.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}

      - run:
          name: Run tests
          command: mvn -q clean test
          when: always

      - run:
          name: Generate Allure HTML report
          command: mvn -q allure:report
          when: always

      - run:
          name: Create report entrypoint
          command: |
            mkdir -p target/allure-report-entry
            REPORT_DIR="target/site/allure-maven-plugin"
            if [ -f "${REPORT_DIR}/index.html" ]; then
              cp "${REPORT_DIR}/index.html" target/allure-report-entry/latest.html
            fi
          when: always

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/allure-results
          destination: allure-results

      - store_artifacts:
          path: target/site/allure-maven-plugin
          destination: allure-report

      - store_artifacts:
          path: target/allure-report-entry/latest.html
          destination: allure-report/latest.html

      - save
